name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            packages/rust-core/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Run Rust tests
        run: cd packages/rust-core && cargo test

      - name: Build all packages
        run: npm run build

      - name: Run linting
        run: npm run lint || echo "Linting completed with warnings"

  build-matrix:
    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: |
              cd packages/rust-core
              npx napi build --platform --release --target x86_64-unknown-linux-gnu
              ls -la *.node || echo "No .node files found yet"
              find . -name "*.node" -exec strip {} \; || echo "Strip completed or no files to strip"
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              cd packages/rust-core
              npx napi build --platform --release --target x86_64-apple-darwin
              ls -la *.node || echo "No .node files found yet"
              find . -name "*.node" -exec strip -x {} \; || echo "Strip completed or no files to strip"
          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              cd packages/rust-core
              npx napi build --platform --release --target aarch64-apple-darwin
              ls -la *.node || echo "No .node files found yet"
              find . -name "*.node" -exec strip -x {} \; || echo "Strip completed or no files to strip"
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: |
              cd packages/rust-core
              npx napi build --platform --release --target x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            packages/rust-core/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Build native module
        run: ${{ matrix.settings.build }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.settings.target }}
          path: packages/rust-core/*.node
          if-no-files-found: warn
