/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type LiveTSEngine = LiveTsEngine
/** The main LiveTS engine that coordinates all core functionality */
export declare class LiveTsEngine {
  /** Creates a new LiveTS engine instance */
  constructor()
  /** Renders a component and returns the diff patches */
  renderComponent(componentId: string, oldHtml: string, newHtml: string): Array<number>
}
